name: SimpleSpawn
main: me.ellbristow.SimpleSpawn.SimpleSpawn
version: 1.0.2
author: ellbristow
dev-url: http://dev.bukkit.org/server-mods/simplespawn
description: >
             Set the world's spawn location.
commands:
  setspawn:
    description: Set spawn location.
    permission: simplespawn.set
  spawn:
    description: Teleport to spawn location.
    permission: simplespawn.use
  sethome:
    description: Set home location.
    permission: simplespawn.home.set
  home:
    description: Teleport to home location.
    permission: simplespawn.home.use
permissions:
  simplespawn.*:
    description: Access to all SimpleSpawn commands.
    children:
      simplespawn.set: true
      simplespawn.use: true
      simplespawn.home.set: true
      simplespawn.home.use: true
  simplespawn.home.*:
    description: Access to /home and /sethome.
    children:
      simplespawn.home.set: true
      simplespawn.home.use: true
  simplespawn.set:
    description: Access to /setspawn.
  simplespawn.use:
    description: Access to /spawn.
  simplespawn.home.set:
    description: Access to /sethome.
  simplespawn.home.use:
    description: Access to /home.
